# Uncomment the next line to define a global platform for your project
 platform :ios, ’10.0’

target 'FoodApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

#pod 'PayPal-iOS-SDK'

  # Pods for FoodApp


end

target 'FoodApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FoodApp-tvOS

  target 'FoodApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
